"""empty message

Revision ID: 1212aa4a9d58
Revises: eaff056afe38
Create Date: 2024-03-21 15:13:30.193621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1212aa4a9d58'
down_revision = 'eaff056afe38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
