"""empty message

Revision ID: 147cdcef958e
Revises: 81d023ff0723
Create Date: 2024-03-21 14:36:12.973573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147cdcef958e'
down_revision = '81d023ff0723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=240),
               existing_nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=240),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
