"""empty message

Revision ID: 1d26794174bc
Revises: fc509d61479b
Create Date: 2024-03-18 19:32:27.323835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d26794174bc'
down_revision = 'fc509d61479b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.String(length=120), nullable=True))
        batch_op.drop_column('surface_water')
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('homeworld')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
