"""empty message

Revision ID: 226b55a86726
Revises: f55ce67c8783
Create Date: 2024-03-19 15:00:38.488363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226b55a86726'
down_revision = 'f55ce67c8783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
