"""empty message

Revision ID: d2bc9f3ab465
Revises: 33afa6b1c917
Create Date: 2024-03-18 18:57:12.021703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bc9f3ab465'
down_revision = '33afa6b1c917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=120), nullable=True))
        batch_op.drop_column('skin_color')
        batch_op.drop_column('weight')
        batch_op.drop_column('homeworld')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('gender')
        batch_op.drop_column('hair_color')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.String(length=120), nullable=True))
        batch_op.drop_column('diamete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diamete', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('diameter')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('homeworld', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('surface_water')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###
