"""empty message

Revision ID: e3e967c94b42
Revises: b2464d71b831
Create Date: 2024-03-21 13:56:52.238061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e967c94b42'
down_revision = 'b2464d71b831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('surface_water')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')

    # ### end Alembic commands ###
