"""empty message

Revision ID: eaff056afe38
Revises: fad669ff22cd
Create Date: 2024-03-21 15:11:18.937555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaff056afe38'
down_revision = 'fad669ff22cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=True))
        batch_op.drop_column('url_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
