"""empty message

Revision ID: fad669ff22cd
Revises: 147cdcef958e
Create Date: 2024-03-21 15:07:23.420128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad669ff22cd'
down_revision = '147cdcef958e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.Integer(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('url_id')

    # ### end Alembic commands ###
